{% set name = "yt-dlp" %}
{% set version = "2024.10.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0baf1ab517c9748d7e337ced91c5543c36fc16246a9ebedac32ebf20c1998ceb

build:
  number: 0
  noarch: python
  entry_points:
    - yt-dlp = yt_dlp:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - brotli
    - brotlicffi
    - certifi
    - mutagen
    - pycryptodomex
    - requests <3,>=2.32.2
    - urllib3 >=1.26.17,<3
    - websockets >=13.0

test:
  imports:
    - yt_dlp
    - yt_dlp.compat
  commands:
    - pip check
    - yt-dlp --help
    - yt-dlp --version
  requires:
    - pip

about:
  home: https://github.com/yt-dlp/yt-dlp
  summary: A youtube-dl fork with additional features and patches
  dev_url: https://github.com/yt-dlp/yt-dlp
  license: Unlicense
  license_file: LICENSE
  description: yt-dlp is a youtube-dl fork based on the now inactive youtube-dlc. The main focus of this project is adding new features and patches while also keeping up to date with the original project

extra:
  recipe-maintainers:
    - HeavyTony2
